# Copyright Dome Systems.
#
# Dome Private License (D-PL) [a369] PubPL 36 (7 Gallium 369)
#
# * URL: http://csgames.org/2016/dome_license.md
# * Type: Software
# * Media: Software
# * Origin: Mines of Morriar
# * Author: Morriar

compile:
	mkdir -p bin/
	nitc src/pear_map.nit -o bin/pear_map

check:
	./tests.sh

clean:
	rm -rf bin/ out/
