.sitanenev adivarg sutcel te otsuj muiterp saneceaM .susir sore ue maN .seicirtlu di siruam ca mutnemidnoc euqsetnelleP .iud tu isin ucra tirerdneh tu ,oido suirav orebil tilev ,ranivlup sittigas tema tis tile ,ruticiffe deS .orebil xe ca sullesahP .isilicaf alluN .tilev adivarg ca mauqilA .reprocmallu odommoc ropmet saneceaM .xe di sucal orebil niduticillos di ,assam atrop hbin tilev ,alucihev mutcid tema tis muspi ,susruc siuD .supmet sullet euqsetnellep subipad ,arreviv mine cen iud suirav nI .tile gnicsipida rutetcesnoc ,tema tis rolod muspi meroL

.soeanemih sotpecni rep ,artson aibunoc rep tneuqrot arotil da uqsoicos iticat tnetpa ssalC .non mulubitsev sullet seicirtlu ca ,sutcel alugil subipad cenoD .allignirf alucihev a tile arterahp euqsiuQ .siprut tnudicnit tema tis sullesahP .supmet seicirtlu mauq ruticiffe di ,neipas im arreviv cenoD .supmet ropmet angam odommoc orebil te euqsetnelleP .sucal des eativ teidrepmi rotcua rotrot teidrepmi sucal ca ecsuF .rolod tidnalb cen cnuN .ue missingid alugil rotittrop tege ,mauq oido tnudicnit cenoD .eitselom merol sucnohr des ,mutnemele oel te euqen arterahp deS .subicuaf ni simirp muspi etna ca semaf adauselam te mudretnI

.tu mutnemidnoc isin mauqila a ,icro sullet alucihev tU .non ropmet angam mutnemele a ,ucra alugil ruticiffe saneceaM .sullet ca ca mutnemidnoc missingid etna des sore di deS .euqsetnellep ue hbin non euqsetnellep sarC .otsuj sullet a cenoD .tilev te sullet euqen tarecalp a ,sutcel arterahp etna sutcel ,ereusop subicuaf te tare ,tauqesnoc sarC .tidnalb susruc ucra ni rotrot ta saneceaM .sisilicaf rutetcesnoc sutem ca oel ereusop deS .mauq sitanenev ,a iud tipicsus ,reprocmallu lsin te essidnepsuS .sitanenev repmes siruam sitrobol ca ,susir rotrot eranro alluN

.isilicaf alluN .non ereusop lsin domsiue a ,merol susir dnefiele deS .tile gnicsipida rutetcesnoc ,tema tis rolod muspi meroL .iud ta ni reprocmallu murtur im ta iud a alluN .mutnemidnoc cen silef di etatupluv maN .mutnemref siuq mine cen taptulov cenoD .tile gnicsipida rutetcesnoc ,tema tis rolod muspi meroL .eativ mutcid icro adivarg non ,muspi missingid alucihev malluN .isin tema tis isin hbin atrop ta ,sutcel ropmet merol euqen ,adivarg ranivlup a sore ,mutnemele euqsetnelleP .anru mutnemidnoc siuq saneceaM .cen reprocmallu rotrot teidrepmi ca ,rolod sutem nasmucca essidnepsuS .rolod murtur ta rutibaruC

.tipicsus tnudicnit subinif sumaviV .ucra susir tege nI .mutnemref sumixam sutem tege euqen eranro sullesahP .lev tnudicnit iud sitanenev tu ,eugua arterahp ranivlup cnuN .subicuaf susruc tu sullet sumixam sarC .des tauqesnoc susir repmes non ,surup rotrot sisilicaf tnesearP .rotrot selados subicuaf alluN .ta sillavnoc im seicirtlu di ,assam lsin nasmucca tU .tarecalp lev mine adivarg sillom nI
