<class 'alveoli_defs.AntiRadiationCell'>
	capacity: 10
	identifier: 1
	wave: alpha
<class 'alveoli_defs.SunCell'>
	capacity: 10.1
	luminosity: 23
<class 'alveoli_defs.EnergyCell'>
	capacity: 11
	radcell_id: 1
<class 'alveoli_defs.AntiNonCitizenCell'>
	current_health: 10
	kill_count: 10
