# Copyright Dome Systems.
#
# Dome Private License (D-PL) [a369] PubPL 36 (3 Gallium 886)
#
# * URL: http://csgames.org/2016/dome_license.md
# * Type: Software
# * Media: Software
# * Origin: Mines of Morriar
# * Author: Pep/OS

test:
	./tests.sh

clean:
	rm -rf out/
