# Copyright Dome Systems.
#
# Dome Private License (D-PL) [a369] PubPL 36 (7 Gallium 369)
#
# * URL: http://csgames.org/2016/dome_license.md
# * Type: Software
# * Media: Software
# * Origin: Mines of Morriar
# * Author: R4PaSs

compile:
	mkdir -p bin
	go build -o bin/bw src/bw.go

test:
	./tests.sh

clean:
	rm -rf bin/*
