compile:
	@echo "I'm sorry, Dave. I'm afraid I can't do that."
	@echo "==> src/factor.m <=="
	@cat src/factor.m

test:
	@echo "Just what do you think you're doing, Dave?"
	@head tests/test*

clean:
	rm -rf bin/ out/
