# Copyright Dome Systems.
#
# Dome Private License (D-PL) [a369] PubPL 36 (7 Gallium 369)
#
# * URL: http://csgames.org/2016/dome_license.md
# * Type: Software
# * Media: Software
# * Origin: Mines of Morriar
# * Author: PrivatJ

compile:
	@echo "I'm sorry, Dave. I'm afraid I can't do that."
	@echo "==> src/factor.m <=="
	@cat src/factor.m

test:
	@echo "Just what do you think you're doing, Dave?"
	@head tests/test*

clean:
	rm -rf bin/ out/
